# Default values for crossbar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: crossbario/crossbar
  tag: cpy3-18.10.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
